import React, {Component} from 'react';
import { StyleSheet, View, Image, Button, FlatList, TouchableOpacity } from 'react-native';
import { Text, Card, Divider } from 'react-native-elements';
import FontAwesome5 from 'react-native-vector-icons/FontAwesome5';

import Moment from 'moment';

import { CardStyles as styles } from '../themes/CardStyles' 

// This map is autogenerated from CDC data using the script in
//   universal-verifier-app/scripts/generate_vaccine_map.py
// See comments in that script to update.
const VACCINE_CODES = {
	2	: "ORIMUNE",
	3	: "M-M-R II",
	5	: "ATTENUVAX",
	6	: "MERUVAX II",
	7	: "MUMPSVAX",
	8	: "ENGERIX B-PEDS; RECOMBIVAX-PEDS",
	9	: "TDVAX; Td, adsorbed",
	10	: "IPOL",
	18	: "Imovax; RabAvert",
	19	: "MYCOBAX; TICE BCG",
	20	: "ACEL-IMUNE; CERTIVA; INFANRIX; TRIPEDIA",
	21	: "VARIVAX",
	22	: "TETRAMUNE",
	24	: "BIOTHRAX",
	25	: "VIVOTIF BERNA; Vivotif",
	28	: "DT(GENERIC)",
	32	: "MENOMUNE",
	33	: "PNEUMOVAX 23",
	35	: "TETANUS TOXOID (GENERIC)",
	37	: "YF-VAX",
	38	: "BIAVAX II",
	39	: "JE-VAX",
	40	: "IMOVAX ID",
	43	: "ENGERIX-B-ADULT; RECOMBIVAX-ADULT",
	44	: "RECOMBIVAX-DIALYSIS",
	46	: "PROHIBIT",
	47	: "HIBTITER",
	48	: "ACTHIB; HIBERIX; OMNIHIB",
	49	: "PEDVAXHIB",
	50	: "TRIHIBIT",
	51	: "COMVAX",
	52	: "HAVRIX-ADULT; VAQTA-ADULT",
	53	: "TYPHOID-AKD",
	56	: "DENGVAXIA",
	62	: "GARDASIL",
	75	: "ACAM2000; DRYVAX",
	83	: "HAVRIX-PEDS; VAQTA-PEDS",
	94	: "PROQUAD",
	100	: "PREVNAR 7",
	101	: "TYPHIM VI",
	104	: "TWINRIX",
	106	: "DAPTACEL",
	110	: "PEDIARIX",
	111	: "FLUMIST",
	113	: "DECAVAC; Tenivac",
	114	: "MENACTRA",
	115	: "ADACEL; BOOSTRIX",
	116	: "ROTATEQ",
	118	: "CERVARIX",
	119	: "ROTARIX",
	120	: "PENTACEL",
	121	: "ZOSTAVAX",
	125	: "Novel Influenza-H1N1-09, nasal",
	126	: "Novel influenza-H1N1-09, preservative-free",
	127	: "Novel influenza-H1N1-09",
	130	: "KINRIX; Quadracel",
	133	: "PREVNAR 13",
	134	: "IXIARO; Ixiaro",
	135	: "FLUZONE-HIGH DOSE",
	136	: "MENVEO; Menveo",
	140	: "AGRIFLU; Afluria, preservative free; FLUARIX; FLUVIRIN-PRESERVATIVE FREE; FLUZONE-PRESERVATIVE FREE; Flulaval, preservative free; Fluvirin preservative free",
	141	: "AFLURIA; Afluria; FLULAVAL; FLUVIRIN; FLUZONE; Fluvirin",
	143	: "Adenovirus types 4 and 7",
	144	: "Fluzone, intradermal",
	146	: "VAXELIS",
	148	: "MENHIBRIX",
	149	: "Flumist quadrivalent",
	150	: "Afluria quadrivalent preservative free; Fluarix, quadrivalent, preservative free; Flulaval, quadrivalent, preservative free; Fluzone, quadrivalent, preservative free",
	153	: "Flucelvax",
	155	: "Flublok",
	158	: "Afluria, quadrivalent; Flulaval quadrivalent; Fluzone, Quadrivalent",
	160	: "Influenza A (H5N1) -2013; Influenza A monovalent (H5N1), ADJUVANTED-2013",
	161	: "Afluria quadrivalent, preservative free, pediatric; Fluzone Quadrivalent, pediatric",
	162	: "Trumenba",
	163	: "Bexsero",
	165	: "Gardasil 9",
	166	: "Fluzone Quad Intradermal",
	168	: "Fluad",
	171	: "flucelvax, quadrivalent, preservative free",
	174	: "VAXCHORA",
	175	: "IMOVAX",
	176	: "RABAVERT",
	183	: "Stamaril",
	185	: "Flublok quadrivalent",
	186	: "Flucelvax, quadrivalent, with preservative",
	187	: "SHINGRIX",
	189	: "HEPLISAV-B",
	197	: "FLUZONE High-Dose Quadrivalent",
	200	: "FLUZONE Quadrivalent Southern Hemisphere, Pediatric",
	201	: "FLUZONE Quadrivalent Southern Hemisphere",
	202	: "FLUZONE Quadrivalent Southern Hemisphere",
	203	: "MenQuadfi",
	204	: "ERVEBO (Ebola Zaire, Live)",
	205	: "FLUAD Quadrivalent",
	206	: "JYNNEOS",
	207	: "Moderna COVID-19",
	208	: "Pfizer-BioNTech COVID-19",
	210	: "AstraZeneca COVID-19",
	211	: "Novavax COVID-19",
	212	: "Janssen (J&J) COVID-19",
	801	: "AS03 adjuvant"
}

const TRUST_REGISTRY = {
	"https://myvaccinerecord.cdph.ca.gov/creds": "State of California", 
	"https://api.cvshealth.com/smarthealth/v1/card": "CVS Health", 
	"https://covid19.quebec.ca/PreuveVaccinaleApi/issuer": "Province of Quebec",
	"https://smarthealthcard.phsa.ca/v1/issuer":  "Province of British Columbia",
	"https://ekeys.ny.gov/epass/doh/dvc/2021": "State of New York", 
	"https://healthcardcert.lawallet.com": "State of Louisiana",
	"https://epicproxy.et0502.epichosted.com/EPPARRPRD/api/epic/2021/Security/Open/EcKeys/32001/SHC": "UC Health (San Diego / Irvine / Riverside) and Affiliates",
	"https://epicproxy-pub.et0502.epichosted.com/EPPARRPRD/api/epic/2021/Security/Open/EcKeys/32001/SHC": "UC Health (San Diego / Irvine / Riverside) and Affiliates",
	"https://icproxy.mycclink.org/proxy-FHIR/api/epic/2021/Security/Open/EcKeys/32001/SHC": "Contra Costa Health Services",
	"https://proxy.lvh.com/FHIR/api/epic/2021/Security/Open/EcKeys/32001/SHC": "Lehigh Valley Health Network",
	"https://cslinkmobile.csmc.edu/fhirproxy/api/epic/2021/Security/Open/EcKeys/32001/SHC": "Cedars-Sinai Medical Center",
	"https://mychart.uchealth.org": "UCHealth",
	"https://fhir-myrecord.cerner.com/r4/11e960ca-465e-403d-a8ac-dfa9be65dd83": "University of Alabama Hospital",
	"https://fhir-myrecord.cerner.com/r4/Vo3nb7XNL_9G2kQXBPPW3-r0QcpkrCy7": "University of Missouri Health Care",
	"https://fhir-myrecord.cerner.com/r4/7517efed-1048-4d65-8b97-98e147342cf5": "Baptist Health South Florida",
	"https://fhir-myrecord.cerner.com/r4/MgfJfJ70Dbsm4ZMgvz93Y8Q5rmD9yGq5": "Memorial Hermann",
	"https://fhir-myrecord.cerner.com/r4/29a5ccea-f4ab-4447-a191-56b20695970f": "Adventist Health",
	"https://fhir-myrecord.cerner.com/r4/a1b70c2c-780f-4d21-a690-3d71302d3d4f": "CoxHealth",
	"https://fhir-myrecord.cerner.com/r4/fdqklJrzTg5-JsHjn6gcvJbZmmigMGfd": "Dignity Health",
	"https://fhir-myrecord.cerner.com/r4/c93f0ebd-007a-4296-b842-6ac2a4658eb9": "Lafayette General Medical Center",
	"https://fhir-myrecord.cerner.com/r4/Y62ncCuwN85GGa7s0iz44XRnQoc9qr60": "Banner Health",
	"https://fhir-myrecord.cerner.com/r4/0qElfuk7cvLgJndB7hTiCVck6NR0D5uM": "Dignity Health",
	"https://fhir-myrecord.cerner.com/r4/83090b64-9cdb-4df9-93d3-bb2473dfa7f3": "Georgia Regents Health System",
	"https://fhir-myrecord.cerner.com/r4/31d3d17c-a50c-4d78-bc5b-e9716826315e": "Mission Health",
	"https://fhir-myrecord.cerner.com/r4/208486af-ceea-4a7d-b4d7-95c884a327df": "Los Angeles County Department of Health Services",
	"https://fhir-myrecord.cerner.com/r4/072ee25e-9ba2-4626-bd4b-17ff1ccdc763": "My VCU Health",
	"https://fhir-myrecord.cerner.com/r4/-yJKGL5-49LdGDJaxmfdb85K2Njr-hkB": "Alaska Tribal Health System",
	"https://fhir-myrecord.cerner.com/r4/CZXZx6LxE-L3UYv_vYuZuKXOvALyMhgz": "Einstein Healthcare Network",
	"https://fhir-myrecord.cerner.com/r4/4a2476ac-8e51-4591-af31-2fc7fcc3fc0d": "Memorial Hospital",
	"https://fhir-myrecord.cerner.com/r4/4nwOwRkG2bMG2PY-W1zZZrlh0VQphgtr": "University of New Mexico",
	"https://fhir-myrecord.cerner.com/r4/MtxVU3dbzZwHcvfCb2vTAE2_Nwhai9Oq": "North Kansas City Hospital and Meritas Health",
	"https://fhir-myrecord.cerner.com/r4/993df7f9-6163-4b2c-9388-9d472c4ef3f9": "Moffitt Cancer Center",
	"https://fhir-myrecord.cerner.com/r4/136fea15-c667-40bc-9ed2-b1115d62123b": "LifeBridge Health",
	"https://fhir-myrecord.cerner.com/r4/4ec99ef7-2f74-4efb-9ab9-a702c7c570f4": "Broward Health",
	"https://fhir-myrecord.cerner.com/r4/2ae7d625-833b-4a4d-a216-8fc7be3f9894": "Methodist Health System",
	"https://fhir-myrecord.cerner.com/r4/6f2341d3-c614-4a71-9cef-bdca1a222d48": "St. Joseph's Health",
	"https://fhir-myrecord.cerner.com/r4/gF4lFO34tdbrCuznA3JTeuZ_9C_vRKZf": "Truman Medical Centers",
	"https://fhir-myrecord.cerner.com/r4/fjycTxieSBez9BFs-LP0YIikqnvefkZc": "Children's Hospital Los Angeles",
	"https://fhir-myrecord.cerner.com/r4/929sni9vNtBT8k3NbtgAnVZlZv_TYNXC": "Stony Brook Medicine",
	"https://fhir-myrecord.cerner.com/r4/3c2e5608-7636-4d74-9aae-b044a991c609": "Barnabas Health",
	"https://fhir-myrecord.cerner.com/r4/8d8e2b72-238a-4f00-88a3-8ba1a0a2d561": "Cook County Health",
	"https://fhir-myrecord.cerner.com/r4/9997a5fc-aad4-42a6-b005-45276937bbd0": "Olathe Health",
	"https://fhir-myrecord.cerner.com/r4/l0sV4kAP8XYUeDPWgsblj-f2yztSg0Ya": "Borgess Health Alliance Inc.",
	"https://fhir-myrecord.cerner.com/r4/Dbsl25a-uo0gf9Q0PnfwA_QlUbZ5qTHL": "Torrance Memorial",
	"https://fhir-myrecord.cerner.com/r4/3c4a889f-c0c4-4f50-90d1-60f6a5ad9e7d": "Covenant Health",
	"https://fhir-myrecord.cerner.com/r4/d88010de-d791-42d4-b72d-513f9afc5ed1": "Northside Hospital",
	"https://fhir-myrecord.cerner.com/r4/479d1758-f967-4c2c-8306-7960101dd8ca": "University of Tennessee Medical Center",
	"https://fhir-myrecord.cerner.com/r4/idzZ7Xu4K4e6cf6O6PqH5zcqaSD8_vYU": "Columbia St. Mary's",
	"https://fhir-myrecord.cerner.com/r4/5d5c0d2d-0eb7-48af-8536-161bb1a08f58": "Community HealthCare System",
	"https://fhir-myrecord.cerner.com/r4/5ce1dfad-1169-4dc3-a793-3ed399b70e67": "Health Quest",
	"https://fhir-myrecord.cerner.com/r4/53c0399e-61c8-4d87-b605-11883089184d": "My Health Kaweah Health",
	"https://fhir-myrecord.cerner.com/r4/763a86fd-c545-483a-9179-bb60864b329a": "Maury Regional Health",
	"https://fhir-myrecord.cerner.com/r4/d63001e8-2b2d-46b2-9b8b-4bc37428b829": "Munson Healthcare",
	"https://fhir-myrecord.cerner.com/r4/c1a92d40-9e4c-42a9-a69d-27d782800e16": "St. John's Health",
	"https://fhir-myrecord.cerner.com/r4/db9c2801-7026-47b6-a85f-5d485070d969": "Western Connecticut Health Network",
	"https://fhir-myrecord.cerner.com/r4/a03a0cab-f0e8-4c09-b504-1f5b4ebcf684": "Ascension",
	"https://fhir-myrecord.cerner.com/r4/1co7TB-AnE4kKYvBDzXBJf-MlYrYrEnf": "Crittenton Hospital Medical Center",
	"https://fhir-myrecord.cerner.com/r4/UMZ-Uxn6V9x08sH5gCnG-5yPg9ZX7et6": "NorthBay Healthcare",
	"https://fhir-myrecord.cerner.com/r4/mP6IHJrv4n0_mPZFBm5GcbTX3TNMQJqa": "Aultman",
	"https://fhir-myrecord.cerner.com/r4/d04f75c7-2a62-4686-b520-7bf0635f38f0": "Lowell General Hospital",
	"https://fhir-myrecord.cerner.com/r4/c5cd8f23-ae54-4fcb-84cc-92eea9354e2b": "MIT Medical",
	"https://fhir-myrecord.cerner.com/r4/2ee676c7-a169-4238-a242-e953ca559f22": "Tenet Healthcare Corporation",
	"https://fhir-myrecord.cerner.com/r4/4a0f2b1c-3433-4080-963d-5ef416dec69b": "SoutheastHEALTH",
	"https://fhir-myrecord.cerner.com/r4/dcf3b1c6-3971-4673-962e-8b2cce0ff827": "Wyoming Medical Center",
	"https://fhir-myrecord.cerner.com/r4/5b3de6b7-e81f-4297-bc82-78ac9e1083cc": "Roper St. Francis Healthcare",
	"https://fhir-myrecord.cerner.com/r4/0e5efebe-b60c-458e-971a-ee39e08a2178": "Westchester Medical Center Health Network",
	"https://fhir-myrecord.cerner.com/r4/70091b8b-c363-42f8-b4d5-3b99f0fb60f1": "Clara Barton Hospital",
	"https://fhir-myrecord.cerner.com/r4/5bb47b8f-8587-42a0-80df-8d4eecf69db3": "Capital Health",
	"https://fhir-myrecord.cerner.com/r4/86c11601-5c46-46d5-a746-706bd2e9f00b": "East Jefferson General Hospital",
	"https://fhir-myrecord.cerner.com/r4/iNB6hL-tYJggf7je2gx1HftngxiOxAQ3": "Lawrence Memorial Hospital",
	"https://fhir-myrecord.cerner.com/r4/rbydrzVcVSCNsdQAe12aQKnP6ZixR1Uf": "MyNCH Health Portal",
	"https://fhir-myrecord.cerner.com/r4/2RN95TVx9sVNwZUXvBjAMhoPj5vjnRtA": "University Medical Center",
	"https://fhir-myrecord.cerner.com/r4/8d555f5f-2441-4690-bfdd-d2697379c3d6": "University of South Alabama Medical Center",
	"https://fhir-myrecord.cerner.com/r4/4517c430-03bf-4e32-b324-1387cc4e73f3": "Central Maine Healthcare",
	"https://fhir-myrecord.cerner.com/r4/R0BnjtS1Cg4P990d7iegvoMVqlnOQ9OI": "Billings Clinic",
	"https://fhir-myrecord.cerner.com/r4/fca878a1-6c97-4ecb-b6e7-eb5d7cde15ab": "Huntsville Hospital Health System",
	"https://fhir-myrecord.cerner.com/r4/46286911-5e07-45f3-b3ed-613a98a13430": "Logansport Memorial Hospital",
	"https://fhir-myrecord.cerner.com/r4/e4a5b337-4c87-45bf-ab09-077b7fc19e84": "Monongalia General Hospital",
	"https://fhir-myrecord.cerner.com/r4/a1e8a0f5-46c8-471e-b8cc-601e5d91f41a": "Tenet HealthSystem Medical Inc.",
	"https://fhir-myrecord.cerner.com/r4/977e949f-0f0b-4a36-bf59-4f0819b90ab8": "Kaleida Health",
	"https://fhir-myrecord.cerner.com/r4/1ea8551e-0fb1-4703-8c98-94d25868feac": "Emory Healthcare GOLD Patient Portal",
	"https://fhir-myrecord.cerner.com/r4/1031a3cd-9903-4995-baa5-734895a3e2a2": "Indiana Regional Medical Center",
	"https://fhir-myrecord.cerner.com/r4/19553296-f85a-48c6-9c93-313791e9f18b": "Magruder Hospital",
	"https://fhir-myrecord.cerner.com/r4/AhjJMjQtLMWypw5HhAKlG2VQs9XvM676": "Methodist Le Bonheur Healthcare",
	"https://fhir-myrecord.cerner.com/r4/6f43d0e7-6ff2-489b-abdc-44e8a5e0ca0a": "Rutland Regional Medical Center",
	"https://fhir-myrecord.cerner.com/r4/049ba866-b2ee-406b-80ed-16b97b5d67e5": "Tenet HealthSystem Medical Inc.",
	"https://fhir-myrecord.cerner.com/r4/6f63686c-7a35-4489-8caf-615a181cb733": "Tenet HealthSystem Medical Inc.",
	"https://fhir-myrecord.cerner.com/r4/325e1759-f94c-41b9-87e4-ef568789898b": "Yavapai Regional Medical Center",
	"https://fhir-myrecord.cerner.com/r4/0affe579-9d95-4ec1-b178-1df7328cc0a1": "Blanchard Valley Health System",
	"https://fhir-myrecord.cerner.com/r4/3N1pCmlUG0710nvlzCuO977VaU0tztwr": "Cabell Huntington Hospital and Marshall Health",
	"https://fhir-myrecord.cerner.com/r4/ab208292-75a1-4788-9fc7-1e9a40a7eee3": "Centra Health",
	"https://fhir-myrecord.cerner.com/r4/TtBa6m0CO2ykz03C9oGIAfs1lSi1ZBkp": "Riverside Medical Group",
	"https://fhir-myrecord.cerner.com/r4/ynC9J_dODQE9MboiEOzSXwBNhdrTWHFe": "Detroit Medical Center",
	"https://fhir-myrecord.cerner.com/r4/Frl5JaixaVfSFyjwSToZ4YMYtvsBctDq": "Lakeland Regional Health",
	"https://fhir-myrecord.cerner.com/r4/5ad9a857-21fb-4664-ba2a-5c537d9921b6": "Medical Associates Clinic",
	"https://fhir-myrecord.cerner.com/r4/0d93d980-a159-4c3e-9a19-131175682196": "Margaret Mary Health",
	"https://fhir-myrecord.cerner.com/r4/7771e67c-eed3-4c07-8b39-4ee1de7dfb76": "Pagosa Springs Medical Center",
	"https://fhir-myrecord.cerner.com/r4/b60a46b6-a3df-4cb6-983c-dfcc9a0589e1": "Sarah Bush Lincoln Health Center",
	"https://fhir-myrecord.cerner.com/r4/11ea0cbd-06f9-4ba7-9e47-64230780fa06": "Silver Cross Hospital",
	"https://fhir-myrecord.cerner.com/r4/4ff3b259-e48d-4066-8b35-a6a051f2802a": "My Ascension Seton",
	"https://fhir-myrecord.cerner.com/r4/0857bd9d-3fb8-4b0a-9180-f75d160828c9": "Charleston Area Medical Center",
	"https://fhir-myrecord.cerner.com/r4/d5d04c85-2e0a-49b7-a0e9-5d5feaebb4a4": "Conway Medical Center",
	"https://fhir-myrecord.cerner.com/r4/d0607508-3922-4bbc-924a-d608b5ffe3b7": "United Medical Physicians",
	"https://fhir-myrecord.cerner.com/r4/3fe59471-3589-4f65-b447-b92822bfc057": "Doctors Hospital at Renaissance",
	"https://fhir-myrecord.cerner.com/r4/caa256dd-47f1-49dc-8288-dfc601f2ffbb": "Midwest Medical Center",
	"https://fhir-myrecord.cerner.com/r4/f1bb4645-ebf5-4d16-800a-fd209b7f9cb1": "Henry Community Health",
	"https://fhir-myrecord.cerner.com/r4/52bd19c6-70df-487b-85b8-29be7abf17a1": "Pomona Valley Hospital Medical Center",
	"https://fhir-myrecord.cerner.com/r4/ab796338-ac9c-40c5-863d-ce75caaa302c": "Regional Medical Center",
	"https://fhir-myrecord.cerner.com/r4/2c98a2ec-4d1e-465a-85ea-978418d9b03d": "South Central Regional Medical Center",
	"https://fhir-myrecord.cerner.com/r4/dfb1cd74-983a-49dc-aede-abe989223110": "Tenet HealthSystem Medical Inc.",
	"https://fhir-myrecord.cerner.com/r4/a1e03df3-d2c1-4196-a5dc-f9fb4460babe": "Doctors Care",
	"https://fhir-myrecord.cerner.com/r4/42a1ed53-a9ac-42b2-918f-be592f726951": "Hudson Physicians, S.C",
	"https://fhir-myrecord.cerner.com/r4/18f5d65c-83f0-435a-868c-70ce5a6de90a": "Urology Partners of North Texas",
	"https://fhir-myrecord.cerner.com/r4/44449a6c-e014-4a84-b9a2-5f63676d31de": "Ellis Medicine",
	"https://fhir-myrecord.cerner.com/r4/64706c27-8401-4242-8ca4-f0b7c493efc2": "Fairfield Memorial Hospital",
	"https://fhir-myrecord.cerner.com/r4/30ec54bc-d6f1-41e4-8f29-88104e9b8ee6": "San Juan Regional Medical Center",
	"https://fhir-myrecord.cerner.com/r4/AdmVvrbHriE7AWDLGoyfeuamNXOy9O_a": "Trinity Health North Dakota",
	"https://fhir-myrecord.cerner.com/r4/870ba945-f258-4fb9-a3f5-2c79586392b9": "UHS of Delaware, Inc - Central",
	"https://fhir-myrecord.cerner.com/r4/xYxhuXIFsLg59PaSNJv_x-piAtPKX3W8": "Barnabas Health",
	"https://fhir-myrecord.cerner.com/r4/QvKCOrGcsj2hJ6sASbt18oYJYaBlOEXZ": "Children's National Hospital",
	"https://fhir-myrecord.cerner.com/r4/4680ff74-0924-406e-b918-8a3dc5ea07ee": "Boca Raton Regional Hospital",
	"https://fhir-myrecord.cerner.com/r4/969307fb-b249-4208-b0b4-56a6e3889e8c": "Columbus Regional Healthcare System",
	"https://fhir-myrecord.cerner.com/r4/00bf2f08-38fe-4c4c-8207-96dbe42a9302": "CarolinaEast Medical Center",
	"https://fhir-myrecord.cerner.com/r4/xGC8us00w6i72tkLoWiE0pdWD5WWsJe5": "Marcus Daly Memorial Hospital",
	"https://fhir-myrecord.cerner.com/r4/2e044b81-e4a1-4dfe-8ce3-5d982e938db0": "First Choice Community HealthCare",
	"https://fhir-myrecord.cerner.com/r4/175c9c17-1687-46b3-a9fa-8603ef5296b5": "Hamilton Health Care System",
	"https://fhir-myrecord.cerner.com/r4/b7350dfb-b26c-45d0-a644-be758c7d66ad": "Holland Hospital",
	"https://fhir-myrecord.cerner.com/r4/43b952fe-d2a5-473b-b04a-92c422b758a3": "Katherine Shaw Bethea Hospital",
	"https://fhir-myrecord.cerner.com/r4/80babf0e-2f7d-4b87-9cc1-ea74c9b22a40": "Missouri Delta Medical Center",
	"https://fhir-myrecord.cerner.com/r4/cFBfzd-nLQ_NltNZvtkZioY0NCqOE2kf": "NewYork-Presbyterian Brooklyn Methodist Hospital",
	"https://fhir-myrecord.cerner.com/r4/d09b5303-02b3-4cca-b4b2-ddf355d54e88": "Plumas District Hospital",
	"https://fhir-myrecord.cerner.com/r4/624a554a-fb79-4703-86d3-5d635620055e": "Stony Brook Business Ventures, LLC",
	"https://fhir-myrecord.cerner.com/r4/3518be8a-ee50-46dd-887a-a3e6e4fc9294": "Sturdy Memorial Hospital and Sturdy Memorial Associates",
	"https://fhir-myrecord.cerner.com/r4/Jst2t4B3tQ_LvMKd5zgnH8scFXxFjMAP": "Children's Mercy Hospital",
	"https://fhir-myrecord.cerner.com/r4/94fb32bd-11fc-46c8-aef4-90035a0718bb": "LifePoint Health",
	"https://fhir-myrecord.cerner.com/r4/792eb4ff-2422-4781-8cdc-7969fda08ada": "Asquam Community Health Collaborative",
	"https://fhir-myrecord.cerner.com/r4/h-wugRRmXDZkm9_GMtf9rhlhb3aHTbV5": "Winona Health Services",
	"https://fhir-myrecord.cerner.com/r4/37f6d032-7bca-45b8-891c-69b79d7f4de8": "Mineola District Hospital",
	"https://fhir-myrecord.cerner.com/r4/487b1ee3-44e2-439f-85f0-68e5e235e27a": "University Medical Center of El Paso",
	"https://fhir-myrecord.cerner.com/r4/12e6e189-04bb-431f-917c-32d5c1bc83d5": "Surgery Partners - Nashville",
	"https://fhir-myrecord.cerner.com/r4/d1e1772a-df16-459e-9e9d-ac11507ad967": "Fisher-Titus Medical Center",
	"https://fhir-myrecord.cerner.com/r4/101c0869-4f3e-4fdb-af79-02ba9f712e30": "Chinese Hospital",
	"https://fhir-myrecord.cerner.com/r4/1014839d-07f9-4c12-a617-3f1d8afea267": "San Joaquin General Hospital",
	"https://fhir-myrecord.cerner.com/r4/8bbd570d-db8f-4e0a-abe5-48b447c735fb": "Union General Hospital",
	"https://fhir-myrecord.cerner.com/r4/66620725-6ef3-4a7f-a15f-88b48c4af7dd": "Penn State Health St. Joseph",
	"https://fhir-myrecord.cerner.com/r4/m6q718FZg_-IH-imjhHk1P9jJGSwQzGK": "Wood County Hospital",
	"https://fhir-myrecord.cerner.com/r4/b673e6c7-c87b-498f-86b2-99b24c52c924": "West Tennessee Healthcare",
	"https://fhir-myrecord.cerner.com/r4/bef96e27-b3e6-4b62-ab3e-78a9a16c8040": "Baptist Health",
	"https://fhir-myrecord.cerner.com/r4/WKlSSS89qvhKmD7tJUsOt0whh7EBmDD-": "San Antonio Regional Hospital",
	"https://haiku.scrippshealth.org/ARR-PRD-FHIR/api/epic/2021/Security/Open/EcKeys/32001/SHC": "Scripps Health",
	"https://emrrp.ucdmc.ucdavis.edu/FHIR/api/epic/2021/Security/Open/EcKeys/32001/SHC": "UC Davis Health",
	"https://webservices.dhha.org/PRD-FHIR/api/epic/2021/Security/Open/EcKeys/32001/SHC": "Denver Health",
	"https://epicsoapprd.communitymedical.org/arr_fhir/api/epic/2021/Security/Open/EcKeys/32001/SHC": "Community Medical Centers",
	"https://fhir-myrecord.cerner.com/r4/e6f9b4bf-142e-47be-8246-33cebe5229b6": "Keck Medicine of USC",
	"https://s.bilh.org/healthcard/issuer": "Beth Israel Lahey Health",
	"https://epic-cs.unch.unc.edu/FHIR/api/epic/2021/Security/Open/EcKeys/32001/SHC": "UNC Health Care System",
	"https://epicfhir.unitypoint.org/ProdFHIR/api/epic/2021/Security/Open/EcKeys/32001/SHC": "UnityPoint Health",
	"https://myc.ochsner.org/FHIR/api/epic/2021/Security/Open/EcKeys/32001/SHC": "Ochsner Health System",
	"https://fhir-myrecord.cerner.com/r4/c2a9aaad-29f4-4d5d-87b0-388c13a9b433": "MedStar Health",
	"https://healthy.kaiserpermanente.org/public-keys/shc/v1": "Kaiser Permanente",
	"https://epicproxy.et1073.epichosted.com/FHIRProxy/api/epic/2021/Security/Open/EcKeys/32001/SHC": "Englewood Hospital and Medical Center",
	"https://EpicFHIR.aurora.org/FHIR/api/epic/2021/Security/Open/EcKeys/32001/SHC": "Advocate Aurora Health",
	"https://patientfhirapis.ynhh.org/PFF/api/epic/2021/Security/Open/EcKeys/32001/SHC": "Yale New Haven Health System and Yale University",
	"https://linkpoint.ghcscw.com/Interconnect-PRD-FHIR/api/epic/2021/Security/Open/EcKeys/32001/SHC": "Group Health Cooperative - South Central Wisconsin",
	"https://epicproxy.et0965.epichosted.com/FHIRProxy/api/epic/2021/Security/Open/EcKeys/32001/SHC": "BJC HealthCare and Washington University Physicians",
	"https://unified-api.ucsf.edu/clinical/apex/api/epic/2021/Security/Open/EcKeys/32001/SHC": "UCSF Health",
	"https://soap.phci.org/Interconnect-FHIR/api/epic/2021/Security/Open/EcKeys/32001/SHC": "ProHealth",
	"https://hygieia.bronsonhg.org/FHIRProxy/api/epic/2021/Security/Open/EcKeys/32001/SHC": "Bronson Healthcare Group",
	"https://epproxy.texashealth.org/FHIR/api/epic/2021/Security/Open/EcKeys/32001/SHC": "Texas Health Resources",
	"https://hie.hcmed.org/FHIR/api/epic/2021/Security/Open/EcKeys/32001/SHC": "Hennepin Healthcare",
	"https://epicproxy.et0978.epichosted.com/FHIRProxy/api/epic/2021/Security/Open/EcKeys/32001/SHC": "UMass Memorial Health",
	"https://ccpintconfg.ohiohealth.com/Interconnect-PRD-MUAPI/api/epic/2021/Security/Open/EcKeys/32001/SHC": "OhioHealth",
	"https://ssproxy.osfhealthcare.org/fhir-proxy/api/epic/2021/Security/Open/EcKeys/32001/SHC": "OSF HealthCare",
	"https://epicproxy.et1123.epichosted.com/FHIRProxy/api/epic/2021/Security/Open/EcKeys/32001/SHC": "AltaMed",
	"https://epic-soap.uchealth.com/FHIRProxy/api/epic/2021/Security/Open/EcKeys/32001/SHC": "UC Health (Cincinnati)",
	"https://healthy.kaiserpermanente.org/public-keys/shc/v1/api/epic/2021/Security/Open/EcKeys/32001/SHC": "Kaiser Permanente",
	"https://haikuwa.providence.org/fhirproxy/api/epic/2021/Security/Open/EcKeys/32001/SHC": "Providence St. Joseph Health",
	"https://haikuor.providence.org/fhirproxy/api/epic/2021/Security/Open/EcKeys/32001/SHC": "Providence St. Joseph Health",
	"https://haikuak.providence.org/fhirproxy/api/epic/2021/Security/Open/EcKeys/32001/SHC": "Providence St. Joseph Health",
	"https://minerva.northmemorial.com/fhir/api/epic/2021/Security/Open/EcKeys/32001/SHC": "North Memorial Health",
	"https://pvc.service.yukon.ca/issuer": "Government of Yukon",
	"https://sehproxy.stelizabeth.com/arr-fhir/api/epic/2021/Security/Open/EcKeys/32001/SHC": "St. Elizabeth Healthcare",
	"https://epicarr02.spectrumhealth.org/EpicFHIR/api/epic/2021/Security/Open/EcKeys/32001/SHC": "Spectrum Health",
	"https://epicproxy.uvmhealth.org/FHIR-ARR/api/epic/2021/Security/Open/EcKeys/32001/SHC": "The University of Vermont Medical Center",
	"https://epicproxy.et1058.epichosted.com/FHIRProxy/api/epic/2021/Security/Open/EcKeys/32001/SHC": "Montage Health",
	"https://epicservicegw.froedtert.com/FHIRproxyPRD/api/epic/2021/Security/Open/EcKeys/32001/SHC": "Froedtert Health",
	"https://rxedi.bmhcc.org/prd-fhir/api/epic/2021/Security/Open/EcKeys/32001/SHC": "Baptist Memorial Health Care",
	"https://iatrius.atriushealth.org/FHIR/api/epic/2021/Security/Open/EcKeys/32001/SHC": "Atrius Health",
	"https://uhealthsoap.med.miami.edu/FHIRProxy/api/epic/2021/Security/Open/EcKeys/32001/SHC": "UHealth – University of Miami Health System",
	"https://epicfhir.phs.org/FHIR/api/epic/2021/Security/Open/EcKeys/32001/SHC": "Presbyterian Healthcare Services",
	"https://epicproxy.et1057.epichosted.com/FHIRProxy/api/epic/2021/Security/Open/EcKeys/32001/SHC": "Molina Healthcare",
	"https://haiku.sparrow.org/fhir-prd/api/epic/2021/Security/Open/EcKeys/32001/SHC": "Sparrow Health System",
	"https://eprescribe-p.medisys.org/fhir-prd/api/epic/2021/Security/Open/EcKeys/32001/SHC": "MediSys Health Network",
	"https://fhirprd.edward.org/fhirprd/api/epic/2021/Security/Open/EcKeys/32001/SHC": "DuPage Medical Group and Edward-Elmhurst Health",
	"https://apps.vdh.virginia.gov/credentials": "Virginia Department of Health",
	"https://webservices.hawaiipacifichealth.org/fhir/api/epic/2021/Security/Open/EcKeys/32001/SHC": "Hawaii Pacific Health",
	"https://mhssp.mhs.net/fhir/api/epic/2021/Security/Open/EcKeys/32001/SHC": "Memorial Healthcare System",
	"https://eparp.sbch.org/FHIR/api/epic/2021/Security/Open/EcKeys/32001/SHC": "Cottage Health",
	"https://ep-rpfg.rivhs.com/Interconnect-FHIR-PRD/api/epic/2021/Security/Open/EcKeys/32001/SHC": "Riverside Health System",
	"https://fhir.ssmhc.com/Fhir/api/epic/2021/Security/Open/EcKeys/32001/SHC": "SSM Health",
	"https://epincoming.slhs.org/Interconnect-FHIR/api/epic/2021/Security/Open/EcKeys/32001/SHC": "St. Luke’s Health System (Idaho)",
	"https://fhir.lakelandregional.org/fhirproxy/api/epic/2021/Security/Open/EcKeys/32001/SHC": "Spectrum Health Lakeland",
	"https://eproxy.mercycare.org/oauth2/api/epic/2021/Security/Open/EcKeys/32001/SHC": "Mercy Medical Center",
	"https://fhir.seattlechildrens.org/fhir/api/epic/2021/Security/Open/EcKeys/32001/SHC": "Seattle Children’s",
	"https://fhir.guthrie.org/FHIR-PRD/api/epic/2021/Security/Open/EcKeys/32001/SHC": "The Guthrie Clinic",
	"https://api.baptist-health.org/Interconnect-FHIR/api/epic/2021/Security/Open/EcKeys/32001/SHC": "Baptist Health",
	"https://www.riteaid.com": "Rite Aid Pharmacy",
	"https://epicproxy.et1134.epichosted.com/FHIRProxy/api/epic/2021/Security/Open/EcKeys/32001/SHC": "Phelps Health",
	"https://epicproxy-pub.et1089.epichosted.com/FHIRProxy/api/epic/2021/Security/Open/EcKeys/32001/SHC": "New York Consortium",
	"https://epicproxy.et1124.epichosted.com/FHIRProxy/api/epic/2021/Security/Open/EcKeys/32001/SHC": "Middlesex Health",
	"https://epic-p-foreground.centura.org/prd-fhir/api/epic/2021/Security/Open/EcKeys/32001/SHC": "Centura Health",
	"https://ovc-api.optum.com/imm/ocm/issuer": "United Healthcare Services, Inc.",
	"https://skphr.prd.telushealthspace.com": "eHealth Saskatchewan",
	"https://commons.ehealthsask.ca": "eHealth Saskatchewan",
	"https://moc.beaumont.org/FHIR/api/epic/2021/Security/Open/EcKeys/32001/SHC": "Beaumont Health",
	"https://interconnect.wellspan.org/interconnect-prd-fhir/api/epic/2021/Security/Open/EcKeys/32001/SHC": "WellSpan Health",
	"https://scproxy.gundersenhealth.org/FHIRARR/api/epic/2021/Security/Open/EcKeys/32001/SHC": "Gundersen Health System",
	"https://epicproxy.hosp.wisc.edu/FhirProxy/api/epic/2021/Security/Open/EcKeys/32001/SHC": "UW Health",
	"https://epicmobile.centracare.com/fhir/api/epic/2021/Security/Open/EcKeys/32001/SHC": "CentraCare",
	"https://epic-rproxyprod.coh.org/Interconnect-FHIR-PRD/api/epic/2021/Security/Open/EcKeys/32001/SHC": "City of Hope",
	"https://epicprisfd01.wpahs.org/PRD-FHIR/api/epic/2021/Security/Open/EcKeys/32001/SHC": "Allegheny Health Network",
	"https://epic-arr.utmb.edu/fhir-prd/api/epic/2021/Security/Open/EcKeys/32001/SHC": "University of Texas Medical Branch",
	"https://prd.salemhealth.org/fhir/api/epic/2021/Security/Open/EcKeys/32001/SHC": "Salem Health",
	"https://rx.premierhealthpartners.org/fhir/api/epic/2021/Security/Open/EcKeys/32001/SHC": "Premier Health",
	"https://sshic.southshorehealth.org/FHIR/api/epic/2021/Security/Open/EcKeys/32001/SHC": "South Shore Health",
	"https://epicsoap.carle.com/FHIR/api/epic/2021/Security/Open/EcKeys/32001/SHC": "Carle Foundation Hospital",
	"https://apiservices.sutterhealth.org/ifs/api/epic/2021/Security/Open/EcKeys/32001/SHC": "Sutter Health",
	"https://common.virginiahospitalcenter.com/FHIRPRD/api/epic/2021/Security/Open/EcKeys/32001/SHC": "Virginia Hospital Center",
	"https://epicproxy.et0830.epichosted.com/FHIRProxy/api/epic/2021/Security/Open/EcKeys/32001/SHC": "Franciscan Missionaries of Our Lady Health System, Inc.",
	"https://epicproxy.et0996.epichosted.com/FHIRProxy/api/epic/2021/Security/Open/EcKeys/32001/SHC": "UConn Health",
	"https://epicproxy.hhchealth.org/FHIR/api/epic/2021/Security/Open/EcKeys/32001/SHC": "Hartford HealthCare",
	"https://epicproxy.mhsjvl.org/FHIRproxy/api/epic/2021/Security/Open/EcKeys/32001/SHC": "Mercyhealth",
	"https://epicproxy.et1038.epichosted.com/FHIRProxy/api/epic/2021/Security/Open/EcKeys/32001/SHC": "EPIC Management",
	"https://EpicIntprxyPRD.swmed.edu/FHIR/api/epic/2021/Security/Open/EcKeys/32001/SHC": "University of Texas Southwestern Medical Center",
	"https://fhir.renown.org/FHIRProxy/api/epic/2021/Security/Open/EcKeys/32001/SHC": "Renown Health",
	"https://interconnect.lcmchealth.org/FHIR/api/epic/2021/Security/Open/EcKeys/32001/SHC": "LCMC Health",
	"https://epicproxy.et1178.epichosted.com/FHIRProxy/api/epic/2021/Security/Open/EcKeys/32001/SHC": "The University of Texas Health Science Center at Houston",
}

export default class SHCCard extends Component {

	patientRecords = () => {
		return this.props.detail.cert.vc.credentialSubject.fhirBundle.entry.filter(entry => entry.resource.resourceType === "Patient");
	}

	otherRecords = () => {
		return this.props.detail.cert.vc.credentialSubject.fhirBundle.entry.filter(entry => entry.resource.resourceType !== "Patient");
	}

	patientName = () => {
		let pat = this.patientRecords();
		return pat[0].resource.name[0].given.join(' ') + " " + pat[0].resource.name[0].family
	}

	patientDob = () => {
		let pat = this.patientRecords();
		// DOB in the local timezone. 
		let localTimezone = new Date().toISOString().split("T");
		return new Date(pat[0].resource.birthDate + "T" + localTimezone[1]);
	}

	issuerName = (card) => {
		if (TRUST_REGISTRY[card.pub_key.toLowerCase()]) {
			return TRUST_REGISTRY[card.pub_key.toLowerCase()]
		}
		return card.pub_key.toLowerCase();
	}

	issuedAt = (card) => {
		return Moment(new Date(parseInt(card.cert.nbf)*1000)).format('MMM DD, YYYY');
	}

	showQR = (card) => {
    this.props.navigation.navigate({name: 'QRShow', params: {
        qr: card.rawQR, 
        title: this.patientName(), 
        detail: "DoB: " + Moment(this.patientDob()).format('MMM DD, YYYY'),
        signedBy: this.issuerName(card) + " on " + this.issuedAt(card)
      }
    });
  }

	renderCard = () => {
		return (
			<View style={[styles.card, {backgroundColor:this.props.colors.primary}]}>
				<View style={{flexDirection:'row', justifyContent:'space-between', alignItems:'center'}}>
					<Text style={styles.notes}>{Moment(this.props.detail.scanDate).format('MMM DD, hh:mma')} - Vaccine Record</Text>
					<FontAwesome5 style={styles.button} name={'trash'} onPress={() => this.props.removeItem(this.props.detail.signature)} solid/>
				</View>

				<View style={{flexDirection:'row', justifyContent:'space-between', alignItems:'center'}}>
					<Text style={styles.title}>{this.patientName()}</Text>
				</View>

				<View style={{flexDirection:'row', justifyContent:'space-between', alignItems:'center'}}>
					<Text style={styles.notes}>DoB: {Moment(this.patientDob()).format('MMM DD, YYYY')}</Text>
				</View>
				
				<Divider style={[styles.divisor, {borderBottomColor:this.props.colors.cardText}]} />

				<FlatList 
					data={this.otherRecords()} 
					keyExtractor={item => item.fullUrl} 
					renderItem={({item}) => {
						return (	
							<View style={styles.groupLine}>
								<View style={styles.row}>
									<Text style={styles.notes}>{item.resource.resourceType} at {item.resource.occurrenceDateTime}</Text>
								</View>
								
								<View style={styles.row}>
									<Text style={styles.notes}>
											Vaccine: {VACCINE_CODES[item.resource.vaccineCode.coding[0].code]}
									</Text>
								</View>

								<View style={styles.row}>
									<Text style={styles.notes}>
											Lot: #{item.resource.lotNumber}
									</Text>
								</View>

								<Divider style={[styles.divisor, {borderBottomColor:this.props.colors.cardText}]} />
							</View>
						)
					}} />
				
				<View style={{flexDirection:'row', alignItems: 'center'}}>
					<FontAwesome5 style={styles.icon} name={'check-circle'} solid/>
					<Text style={styles.notes}>{this.issuerName(this.props.detail)} on {this.issuedAt(this.props.detail)}</Text>
				</View>
			</View>
		);
	}


	render() {
		return this.props.pressable ? 
		( <TouchableOpacity onPress={() => this.showQR(this.props.detail)}>
				{this.renderCard()}
			</TouchableOpacity>
		) : this.renderCard();
	}
}
